# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Typing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Typing
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'JSQMessagesViewController'
	pod 'Firebase/Storage'

  target 'TypingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TypingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
